blank_issues_enabled: true
contact_links:
  - name: BitcoinOil Core Security Policy
    url: https://github.com/bitcoinoil/bitcoinoil/blob/master/SECURITY.md
    about: View security policy
  - name: BitcoinOil Core Developers
    url: https://bitcoincore.org
    about: BitcoinOil Core homepage
