.PHONY: FORCE
all: FORCE
	$(MAKE) -C .. bitcoinoil_qt test_bitcoinoil_qt
clean: FORCE
	$(MAKE) -C .. bitcoinoil_qt_clean test_bitcoinoil_qt_clean
check: FORCE
	$(MAKE) -C .. test_bitcoinoil_qt_check
bitcoinoil-qt bitcoinoil-qt.exe: FORCE
	 $(MAKE) -C .. bitcoinoil_qt
apk: FORCE
	$(MAKE) -C .. bitcoinoil_qt_apk
